import { readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');

async function readSource(relativePath) {
  return readFile(path.join(root, relativePath), 'utf8');
}

function trimTrailingNewlines(value) {
  return value.replace(/\n+$/u, '');
}

function templateLiteralBody(value) {
  return value
    .replace(/`/gu, '\\`')
    .replace(/\$\{/gu, '\\${');
}

function injectStylesSource(css) {
  return [
    '  function injectStyles() {',
    '    if (document.getElementById(`${SCRIPT_ID}-style`)) return;',
    "    const style = document.createElement('style');",
    '    style.id = `${SCRIPT_ID}-style`;',
    '    style.textContent = `',
    templateLiteralBody(trimTrailingNewlines(css)),
    '    `;',
    '    document.head.appendChild(style);',
    '  }',
  ].join('\n');
}

const header = trimTrailingNewlines(await readSource('src/userscript-header.txt'));
const preamble = trimTrailingNewlines(await readSource('src/runtime/preamble.js'));
const styles = [
  await readSource('src/styles.part1.css'),
  await readSource('src/styles.part2.css'),
].join('\n');
const ui = [
  await readSource('src/ui.part1.js'),
  await readSource('src/ui.part2.js'),
].map(trimTrailingNewlines).join('\n\n');
const core = [
  await readSource('src/core.part1.js'),
  await readSource('src/core.part2.js'),
  await readSource('src/core.part3.js'),
].map(trimTrailingNewlines).join('\n\n');
const boot = trimTrailingNewlines(await readSource('src/runtime/boot.js'));

const output = [
  header,
  '',
  '// Generated from src/*. Do not edit this file directly.',
  '// Run `npm run build` after editing source files.',
  '',
  preamble,
  '',
  injectStylesSource(styles),
  '',
  ui,
  '',
  core,
  '',
  boot,
  '})();',
  '',
].join('\n');

await writeFile(path.join(root, 'newapi-helper-suite.user.js'), output);
